### PR TITLE
add digital outputs to NI X-series finite sampling IO

### LINKED ISSUE #93: [New Feature] digital output for nidaq finite sampling io
### Feature Description

The finite sampling input/output hardware file for the nidaq currently supports digital input, analog input as well as analog output. For some cases, it would also be useful to be able to use digital outputs.

Is the nidaq capable of synchronizing digital outputs with the inputs the same way it can synchronize analog outputs with all inputs?

It would be appropriate to adjust `FiniteSamplingIOConstraints` in the interface file accordingly to enforce that samples are boolean only for digital channels.

### Related Problem

Digital outputs could be used for auxiliary purposes during scanning. Specifically, they could be used to trigger an initialization laser pulse before the (analog) frequency scan of a resonant laser in a hardware-synchronized manner.

### Considered Alternatives

Analog channels could be used for the same auxiliary purposes. However, those are limited to four per nidaq (maybe more in some models) and are frequently already occupied by three scanner axes and one laser scan axis.

### Additional Context

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by qku**
## Description

Add the capability to use digital output lines of NI card with finite sampling input/output interface. The channels can be specified as config options. Frame data can be set as arrays of zeros and ones individually and independently for each digital output line. This fixes #93 .

## Motivation and Context

As suggested in #93, using digital output lines of the NI card in a synchronized manner together with analog output, analog input and digital input is useful. Digital output lines can be used as trigger signals for other devices.

## How Has This Been Tested?

This was tested using an NI6343 USB and an oscilloscope to monitor the digital output of up to two individual digital output lines.

## Types of changes

- [ ] Bug fix
- [X] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by qku** [comment]
@qeq-ungar does this satisfy your needs?

**Comment by qku** [comment]
has somebody had a chance to test this? i think this is a nice addition to existing functionality. I am using it to run an experiment involving scanning with an analog voltage + creating pulses with the digital outputs of the NI card.

**Comment by timoML** [comment]
We absolutely plan on merging this. @rmgonzal tested it, but is currently on vacation. We'll keep you posted!

**Comment by rmgonzal** [comment]
I will test this next Monday, I didn't had the time before

**Comment by qku** [comment]
Have you had a chance to test this @rmgonzal ?

**Comment by rmgonzal** [comment]
Hey @qku, sorry for the late reply, I checkout the branch a few weeks ago and everything works so far with my NI PCIe-6323. But I haven't checked properly synchronized digital output lines with finite sampling input/outputs. Do you have a specific task you can give to the NI card so I can properly check it with the oscilloscope? If so would be good you can help me with this

**Comment by qku** [comment]
@rmgonzal thank you for the update! I am happy to hear things are working fine so far.

You could connect a digital output (e.g. P0.0) to a digital/analog input (e.g. PFI0 or ai0) on the same NI card. That way you don't even need an oscilloscope. Write a numpy array consisting of zeros and ones to the digital output, and check whether something similar is read in on the inputs.

I can also provide a notebook snippet for this test, just let me know!

**Comment by qku** [comment]
@rmgonzal could I help at all with my suggestion?

**Comment by qku** [comment]
@rmgonzal have you had a chance yet to look at this again? Let me know if you have any questions or if anything doesn’t work as expected

**Comment by qku** [comment]
I have been waiting on approval of this PR for three months now. Is there any update on your review @rmgonzal @timoML ß

**Review by timoML — DISMISSED** [review]
Sorry for the delay and thanks for your patience. 
We're all volunteering here and fixing errors was a priority recently.
Anyway, we appreciate new contributed functionality and we're trying our best to review. 

@rmgonzal tested that this PR is not interfering with existing functionality.
If the new behavior is working as expected for you, we can merge for now.

**Review by timoML — APPROVED** [review]
Thanks.

**Comment by qku** [comment]
I understand @timoML , fixing bugs is indeed more important than new features! A little bit more communication could be nice such that I know what I can expect from you. Thank you :)

And yes, I have been using this in the lab for a few months now without any more changes! It can be merged.

**Comment by syim70** [comment]
@qku, thanks for the digital outputs feature. It is really an essential one, and I also need the function for triggering devices while scanning. But, I have a trouble to use it. As a python beginner (as well, the qudi, also), it is difficult to understand how to use it. I want to create digital output pulses for every scanning steps, like as you described.

I tried many ways, a few example, 
- Modifying config file: adding "digital_output_lines: - 'port0/line0'"
     -> but, no digital output channel defined
- Modifying ni_scanning_probe_interfuse.py: including `digital_output_lines` in `set_active_channels`
     -> error: keys of data ('ao0', ...) do not match active channels ('ao0', ..., 'port0/line0')

I understand if I can init digital output task and provide non-zero (i.e., 1) numbers to a frame buffer, but I can't find a way. It looks like ni_scanning_probe_interfuse.py does not allow a digital output channel (and sometimes a "channel" means analog inputs only).

Could you let me know how-to, or just post an example? Thanks a lot.

**Comment by qku** [comment]
Hi @syim70, indeed, the `ni_scanning_probe_interfuse` does not support digital output channels. You need to write your own code to implement digital output pulses e.g. before each scan.

However, the good news is that the `ni_finite_sampling_io` now supports digital outputs with this PR. And the scanning probe interfuse is based on the finite sampling io module. Hence you should be able to benefit from the implementation in the finite sampling io hardware module.

What exactly are you trying to achieve? Do you want to add digital trigger pulse into the confocal scan routine?

**Comment by syim70** [comment]
Hi, @qku, thank you for your kind reply. I understand well I need a new code, a modified scanning probe interfuse, as you advised.

As you said well, I want to add digital trigger pulse into the confocal scan routine, that is, one digital pulse per each scan pixel.
Would you please help me?

**Comment by syim70** [comment]
Hi, @qku, I want to make clearer my huddles.

I guess you are successfully using the current version `ni_x_series_finite_sampling_io` to make digital pulses. I understand that `set_active_channels` of the code includes `do_channels`. So, I believe I must define a digital output channel in a "new modified" `ni_scanning_probe_interfuse`. However, `set_frame_data` of `ni_x_series_finite_sampling_io` requires `SamplingOutputMode`, JUMP_LIST or EQUIDSTANT_SWEEP. The both are for analog outputs to make scanning voltages.

Then, how can I add digital output pulse into the confocal scan routine, without modifying `ni_x_series_finite_sampling_io`? Is there a way not to use the above functions?

**Comment by Neverhorst** [comment]
Hi @syim70, hi @qku,

just want to make sure you are not chasing after already existing features.
The digital output capability introduced by this PR covers arbitrary synchronous digital patterns on multiple DO channels.
If you just want to have a sample clock output (i.e. one digital flank per scan pixel), this has already been implemented prior to this PR in the `NIXSeriesFiniteSamplingIO` hardware module as config option `sample_clock_output`. See [the example config](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/425029758a6c831f8d95e6569bfc2a1bfb64071c/src/qudi/hardware/ni_x_series/ni_x_series_finite_sampling_io.py#L85).

**Comment by syim70** [comment]
Hi, @Neverhorst,

I tried your suggestion, monitoring the sample clock signals with an oscilloscope and also with the "APD1" input channel. It works well. I appreciate your kind support.

**Pull request merged**
