### PR TITLE
HighFinesse wavemeter laser control

### PR DESCRIPTION
**Pull request by qku**
## Description

Implement the laser control functionality of HighFinesse wavemeters as PID hardware.

## Motivation and Context

Following the implementation of wavelength readout for the HighFinesse wavemeter, this PR expands the functionality to include laser control. If the option was bought with the device, these wavemeters can output an analog voltage through a DAC card to stabilize the wavelength/frequency of a laser.

## How Has This Been Tested?

Tested with the PID toolchain (gui, logic) and a HighFinesse WS7 while wavelength acquisition with the instreamer was running. Also tested as a remote module.

## Screenshots (only if appropriate, delete if not):
image

## Types of changes

- [ ] Bug fix
- [X] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [X] I have updated the documentation accordingly.
- [X] I have added/updated the config example for any module docstrings as necessary.
- [X] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by qku** [comment]
Is this not of interest to qudi-iqo-modules?

**Comment by Neverhorst** [comment]
Hi @qku , 
on the contrary. Please excuse the long waiting time.
I'm currently writing a laser scanning toolchain based on PRs #120 and #132 but I think this PR is independent of that. 
A standalone PID implementation for this wavemeter should be fine to merge in my opinion, unless @timoML or @ksenkalla want to test this on their hardware first?

**Comment by ksenkalla** [comment]
> Hi @qku , on the contrary. Please excuse the long waiting time. I'm currently writing a laser scanning toolchain based on PRs #120 and #132 but I think this PR is independent of that. A standalone PID implementation for this wavemeter should be fine to merge in my opinion, unless @timoML or @ksenkalla want to test this on their hardware first?

@qku and @onacitarhan17  Thanks for you work on this. I think it is a nice feature. However, in our group we don't have a wavemeter which has the PID feature. So unfortunately I'm not able to test this. From my point of view it is fine if we merge it if there was a code review @Neverhorst .

**Review by Neverhorst — APPROVED** [review]
Looks fine

**Comment by qku** [comment]
I just merged in main again. There where no conflicts apart from the changelog. I still consider this ready to merge @Neverhorst @timoML

**Review by timoML — APPROVED** [review]
Looks good. Thank you.

**Pull request merged**
