### PR TITLE
Fix scanning toolchain issues

### LINKED ISSUE #44: Moving crosshair in Scanning does not update the position in real time
### Version

current main

### What is affected by the bug?

scannergui, scanning_probe_logic, ni_scanning_probe_interfuse

When dragging the crosshair in the scanning GUI it does not always update the scanner position in real time (using NI 6343). 

In the `scanning_probe_logic` the set position function `set_target_position` is called but apparently not always executed properly by the `ni_scanning_probe_interfuse`. It seems like movement is not prepared and maybe there is some threading issues. See the log output below for extended debug messages of the working and not working case. I observe that the bug messages of `_prepare_movement` in the scanning interfuse are not printed when it does not work and also that the `self.thread` `QtCore.QThread.currentThread()` are the same whereas otherwise they are different. I'm not sure whether this might also have an influence but when moving the crosshair faster the `self.__write_queue` sets up and is increasing (until the debug output looks fine) until at a length of between 5 to12 it stops working. 

### When does the bug occur?

Dragging the crosshair in both 2D and 1D scans in an apparently not slow manner. 

### How do we replicate the issue?

Drag the crosshair with the mouse and observe, for example, the PL in a running experiment or better the voltage output of the scanner. 
- dragging it slowly the scanner position (voltage) changes smoothly, 
- dragging faster the scanner position remains constant until the crosshair remains steady for a short time or is let loose.  

### Expected behavior

The scanner position should change uniformly, i.e. according to the movement of the crosshair. 

### Relevant log output

```shell
Working example:
2022-11-08 12:00:28 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Preparing move in thread <PySide2.QtCore.QThread(0x6fb8e31890, name = "mod-logic-scanning_probe_logic") at 0x0000006FC252F840>...
2022-11-08 12:00:28 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Target: {'x': 0.00011014492620845452, 'y': 9.487672341400087e-05}, start: {'x': 0.0001103816, 'y': 8.72627e-05, 'z': 1.5735e-06}
2022-11-08 12:00:28 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Prepared [3, 3] write queue steps  to target= {'x': 0.00011014492620845452, 'y': 9.487672341400087e-05}.
2022-11-08 12:00:28 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Write queue: {'x': array([0.0001103 , 0.00011022, 0.00011014]), 'y': array([8.98007078e-05, 9.23387156e-05, 9.48767234e-05])}
2022-11-08 12:00:28 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse ao start write timer in thread <PySide2.QtCore.QThread(0x6fb8e321c0, name = "mod-hardware-ni_scanner") at 0x0000006FC2567240>, QT.QThread <PySide2.QtCore.QThread(0x6fb8e31890, name = "mod-logic-scanning_probe_logic") at 0x0000006FC252F840> 
2022-11-08 12:00:28 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
2022-11-08 12:00:28 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Started
2022-11-08 12:00:28 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Move finished, returning target.
2022-11-08 12:00:28 debug qudi.logic.scanning_probe_logic.ScanningProbeLogic Logic issuing with id 4888a5e3-4a09-4545-a6ec-df3592fcce83: {'x': 0.00011014492620845452, 'y': 9.487672341400087e-05, 'z': 1.5669e-06}


Not working example:
2022-11-08 12:00:59 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse ao start write timer in thread <PySide2.QtCore.QThread(0x6fb8e321c0, name = "mod-hardware-ni_scanner") at 0x0000006FC2567240>, QT.QThread <PySide2.QtCore.QThread(0x6fb8e321c0, name = "mod-hardware-ni_scanner") at 0x0000006FC2567240> 
2022-11-08 12:00:59 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
2022-11-08 12:00:59 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Started
2022-11-08 12:00:59 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse ao start write timer in thread <PySide2.QtCore.QThread(0x6fb8e321c0, name = "mod-hardware-ni_scanner") at 0x0000006FC2567240>, QT.QThread <PySide2.QtCore.QThread(0x6fb8e321c0, name = "mod-hardware-ni_scanner") at 0x0000006FC2567240> 
2022-11-08 12:00:59 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
2022-11-08 12:00:59 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Started
2022-11-08 12:00:59 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse ao start write timer in thread <PySide2.QtCore.QThread(0x6fb8e321c0, name = "mod-hardware-ni_scanner") at 0x0000006FC2567240>, QT.QThread <PySide2.QtCore.QThread(0x6fb8e321c0, name = "mod-hardware-ni_scanner") at 0x0000006FC2567240> 
2022-11-08 12:00:59 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
2022-11-08 12:00:59 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Started
```

### Additional Comments

Current environment:
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asteval==0.9.27
asttokens==2.0.5
attrs==21.4.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.0
cffi==1.15.0
colorama==0.4.4
cycler==0.11.0
debugpy==1.6.0
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.15.3
fonttools==4.33.3
future==0.18.2
fysom==2.1.6
gitdb==4.0.9
GitPython==3.1.27
importlib-resources==5.7.1
ipykernel==6.14.0
ipython==8.4.0
ipython-genutils==0.2.0
ipywidgets==7.7.0
jedi==0.18.1
Jinja2==3.1.2
jsonschema==4.6.0
jupyter==1.0.0
jupyter-client==7.3.4
jupyter-console==6.4.3
jupyter-core==4.10.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==1.1.0
jupytext==1.13.8
kiwisolver==1.4.3
lmfit==1.0.3
lxml==4.9.0
markdown-it-py==2.1.0
MarkupSafe==2.1.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
mdit-py-plugins==0.3.0
mdurl==0.1.1
mistune==0.8.4
nbclient==0.6.4
nbconvert==6.5.0
nbformat==5.4.0
nest-asyncio==1.5.5
nidaqmx==0.5.7
notebook==6.4.12
numpy==1.22.4
packaging==21.3
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.1.1
plumbum==1.7.2
prometheus-client==0.14.1
prompt-toolkit==3.0.29
protobuf==3.20.1
psutil==5.9.1
pure-eval==0.2.2
pycparser==2.21
Pygments==2.12.0
pyparsing==3.0.9
pyqtgraph==0.12.4
pyrsistent==0.18.1
PySide2==5.15.2
python-dateutil==2.8.2
PyVISA==1.12.0
pywin32==304
pywinpty==2.0.5
PyYAML==6.0
pyzmq==23.1.0
qtconsole==5.3.1
QtPy==2.1.0
-e git+https://github.com/Ulm-IQO/qudi-core.git@2cb2a92d0f4409fcc8ed676ce5ab8216ec826e49#egg=qudi_core
-e git+https://github.com/Ulm-IQO/qudi-iqo-modules.git@390820ce7309fee498499e4ee92478db39a8b75a#egg=qudi_iqo_modules
rpyc==5.1.0
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
Rx==3.2.0
scipy==1.8.1
Send2Trash==1.8.0
shiboken2==5.15.2
six==1.16.0
smmap==5.0.0
soupsieve==2.3.2.post1
stack-data==0.2.0
terminado==0.15.0
tinycss2==1.1.1
toml==0.10.2
tornado==6.1
traitlets==5.2.2.post1
typing-extensions==4.2.0
uncertainties==3.1.6
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.6.0
zaber-motion==2.14.1
zaber-motion-bindings-windows==2.14.1
zipp==3.8.0

In the optimizer (scan order xy, z) the z-scan is done at the initial x,y-position and not the 'optimized' one,  as it is supposed to be. Again `set_target_position` is executed but the scanner doesn't move. After the optimization the x,y-position is the optimized one. Possibly this issue might be related. 

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by timoML**
## Description
- fix a bug that caused sluggy cursor movement by too fast write loop firing timers
- introduce a blocking argument to move_absolute in order to finish optimizer movement before new scan
- ~~drop too fast calls from gui signals to move_absolut(). Better use SignalProxies?~~
- ~~add a minimum size of the scanning crosshair for increased usability~~ -> moved to core

## Motivation and Context
This is the first version of the scanning toolchain that passed internal testing.
Closes #44, #46.

## How Has This Been Tested?
- setup 3
- setup @NicolasStaudenmaier 
- setup @LukePiewalker 

## Types of changes
- [x] Bug fix
- [x] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by timoML** [comment]
Should now also address #46. As this only occurs sponanotusly, some more testing would be appreciated. 
Except for extensive debug messages, I think this PR is ready for review and merge.

**Comment by timoML** [comment]
Another bug while contiously optimizing; occurs every ~ 100 optimizations:

```
2022-11-30 15:14:41 debug qudi.logic.scanning_optimize_logic.ScanningOptimizeLogic Trying to fit on data after scan of dim 1
2022-11-30 15:14:41 debug qudi.logic.scanning_optimize_logic.ScanningOptimizeLogic Optimizer issuing position update: {'z': 6.3845450599609e-05}
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.3845450599609e-05}
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Write loop duration: 0.8359060002476326
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Cursor_write_loop move to {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.3845450599609e-05}, Dist= 1.0849400391001011e-08 took 1.617126999917673 ms.
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Waiting for move to finish.
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Cursor_write_loop stopping at [1.729864e-04 5.316980e-05 6.384550e-05], dist= 4.940039100443522e-11
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Aborting move.
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Move_abs finished after 15.304413000194472 ms at pos= {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.38455e-05}. Target= {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.38455e-05}. |Delta|= 0.0
2022-11-30 15:14:41 debug qudi.logic.scanning_optimize_logic.ScanningOptimizeLogic Next opt sequence step 0
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Start scan with settings {'axes': ('x', 'y'), 'range': ((0.0001726364, 0.0001733364), (5.28198e-05, 5.35198e-05)), 'resolution': (15, 15), 'frequency': 100.0}
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001726364, 'y': 5.31698e-05, 'z': 6.38455e-05}
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001726364, 'y': 5.28198e-05, 'z': 6.38455e-05}
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Write loop duration: 2.463249000356882
2022-11-30 15:14:41 error qudi.logic.scanning_probe_logic.ScanningProbeLogic Unable to change scanner target position while a scan is running.
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Cursor_write_loop move to {'x': 0.0001726364, 'y': 5.28198e-05, 'z': 6.38455e-05}, Dist= 4.949747468305906e-07 took 5.979042000035406 ms.
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Cursor_write_loop stopping at [1.726364e-04 5.281980e-05 6.384550e-05], dist= 0.0
2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Aborting move.
2022-11-30 15:14:51 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001729864, 'y': 5.28198e-05, 'z': 6.38455e-05}
2022-11-30 15:14:51 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.38455e-05}
2022-11-30 15:14:51 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.38455e-05}
2022-11-30 15:14:51 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
```

**Comment by timoML** [comment]
> Another bug while contiously optimizing; occurs every ~ 100 optimizations:
> 
> ```
> 2022-11-30 15:14:41 debug qudi.logic.scanning_optimize_logic.ScanningOptimizeLogic Trying to fit on data after scan of dim 1
> 2022-11-30 15:14:41 debug qudi.logic.scanning_optimize_logic.ScanningOptimizeLogic Optimizer issuing position update: {'z': 6.3845450599609e-05}
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.3845450599609e-05}
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Write loop duration: 0.8359060002476326
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Cursor_write_loop move to {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.3845450599609e-05}, Dist= 1.0849400391001011e-08 took 1.617126999917673 ms.
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Waiting for move to finish.
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Cursor_write_loop stopping at [1.729864e-04 5.316980e-05 6.384550e-05], dist= 4.940039100443522e-11
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Aborting move.
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Move_abs finished after 15.304413000194472 ms at pos= {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.38455e-05}. Target= {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.38455e-05}. |Delta|= 0.0
> 2022-11-30 15:14:41 debug qudi.logic.scanning_optimize_logic.ScanningOptimizeLogic Next opt sequence step 0
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Start scan with settings {'axes': ('x', 'y'), 'range': ((0.0001726364, 0.0001733364), (5.28198e-05, 5.35198e-05)), 'resolution': (15, 15), 'frequency': 100.0}
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001726364, 'y': 5.31698e-05, 'z': 6.38455e-05}
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001726364, 'y': 5.28198e-05, 'z': 6.38455e-05}
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Write loop duration: 2.463249000356882
> 2022-11-30 15:14:41 error qudi.logic.scanning_probe_logic.ScanningProbeLogic Unable to change scanner target position while a scan is running.
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Cursor_write_loop move to {'x': 0.0001726364, 'y': 5.28198e-05, 'z': 6.38455e-05}, Dist= 4.949747468305906e-07 took 5.979042000035406 ms.
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Cursor_write_loop stopping at [1.726364e-04 5.281980e-05 6.384550e-05], dist= 0.0
> 2022-11-30 15:14:41 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Aborting move.
> 2022-11-30 15:14:51 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001729864, 'y': 5.28198e-05, 'z': 6.38455e-05}
> 2022-11-30 15:14:51 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.38455e-05}
> 2022-11-30 15:14:51 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse New target pos: {'x': 0.0001729864, 'y': 5.31698e-05, 'z': 6.38455e-05}
> 2022-11-30 15:14:51 debug qudi.hardware.interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse Starting AO write timer...
> ```

Seems solved after merging #48 into here.

**Review by NicolasStaudenmaier — APPROVED** [review]
Is good.

**Pull request merged**
