### PR TITLE
Zaber motor stages

### PR DESCRIPTION
**Pull request by timoML**
Introduces Zaber motorized stages as supported hardware. To this end, uses the (pretty neat) zaber_motion python package provided by the manufacturer.
Currently, only linear stages are supported. A future extension to rotation stages is possible. 

## How Has This Been Tested?
Tested with real hardware on setup3.

## Types of changes
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by timoML** [comment]
By the way: I think there is currently no changelog for the iqo-modules repo, right?

**Comment by Neverhorst** [comment]
> By the way: I think there is currently no changelog for the iqo-modules repo, right?

Correct. Please feel free to add documentation to this repo. You can take `qudi-core` as example.

**Comment by timoML** [comment]
@Neverhorst: I think it's ready to merge. Tested it for a while now and runs smoothly. Can you approve please?

**Review by Neverhorst — APPROVED** [review]
Looks good

**Pull request merged**
