### PR TITLE
Naming change/fix in Instreamer Toolchain

### PR DESCRIPTION
**Pull request by LukePiewalker**
## Description

Updated the keyword argument in `read_data` of Instream Interface and Dummy from `number_of_samples` to `samples_per_channel`. I assume this was overseen in PR #78 and the only real hardware in main `NIXSeriesInStreamer` is actually already written that way.

Also fixed a bug in the docstring of `read_data` since the arguments of `reshape` were in the wrong order (compare to `read_data_into_buffer`).

## Motivation and Context

Makes the naming consistent within the Instreamer toolchain.
This created problems when testing the `TimeSeriesReaderLogic` in PR #79 where @qku introduced changes to make the logic work with remote modules, which also makes use of `read_data`. Yet in these tests, the changes introduced there, caused errors since the way the `NIXSeriesInStreamer` is written is not complying to the Interface in this function (different keyword argument)

## Types of changes

- [x] Bug fix
- [ ] New feature
- [x] Breaking change (Causes existing functionality to not work as expected)
⚠ Did not update changelog, as I believe it is covered in the changed from PR #78 ⚠

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by qku** [comment]
Awesome! I would have forgotten to create a PR on this :)

**Comment by LukePiewalker** [comment]
Needs the changes from PR #79 though to support a remote instreamer as well to properly test. Sorry for not mentioning so far.

**Review by timoML — APPROVED** [review]
Looks good.

**Comment by qku** [comment]
Looks good to me as well! I tested the reshape command on data from an NI instreamer with two channels to verify that the new docstring is correct.

Would you mind updating `high_finesse_wavemeter.py` as well @LukePiewalker ? It would be as simple as replacing every occurence of `number_of_samples` with `samples_per_channel` and updating the docstring of `read_data`.

**Comment by LukePiewalker** [comment]
> Looks good to me as well! I tested the reshape command on data from an NI instreamer with two channels to verify that the new docstring is correct.
> 
> Would you mind updating `high_finesse_wavemeter.py` as well @LukePiewalker ? It would be as simple as replacing every occurence of `number_of_samples` with `samples_per_channel` and updating the docstring of `read_data`.

Did do so in c80f5d1. Hope I did not forget anything.

**Comment by qku** [comment]
Look good, thank you @LukePiewalker! I also tested this on wavemeter hardware. Ready to merge from my side. Maybe @timoML can give it a last look?

**Pull request merged**
